services:
  - type: web
    name: conversor-pdf-web
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/converson-web-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -XX:+UseG1GC
    autoDeploy: true
